import { User, UserRole, EqubGroup, Transaction, TransactionType, PaymentMethod, ExpenseCategory, Asset, AssetCategory } from './types';

export const MOCK_USERS: User[] = [
  { 
    id: '1', 
    name: 'Abebe Bikila', 
    role: UserRole.SUPER_ADMIN, 
    pin: '1234', 
    email: 'abebe.super@birrtrack.et',
    equityPercentage: 60,
    totalDividendsPaid: 150000,
    joinedDate: '2023-01-01'
  },
  { 
    id: '2', 
    name: 'Sara Tesfaye', 
    role: UserRole.ADMIN, 
    pin: '0000', 
    email: 'sara.admin@birrtrack.et',
    equityPercentage: 25,
    totalDividendsPaid: 45000,
    joinedDate: '2023-03-15'
  },
  { 
    id: '3', 
    name: 'Kebede Molla', 
    role: UserRole.MEMBER, 
    pin: '1111', 
    email: 'kebede.viewer@birrtrack.et',
    equityPercentage: 15,
    totalDividendsPaid: 22000,
    joinedDate: '2023-06-01'
  },
];

export const MOCK_EQUB_GROUPS: EqubGroup[] = [
  {
    id: 'e1',
    name: 'Neighborhood Weekly Equb',
    membersCount: 12,
    currentRound: 4,
    contributionAmount: 1000,
    frequency: 'WEEKLY',
    startDate: '2024-01-01',
    myTurnIndex: 5,
    status: 'ACTIVE'
  }
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    amount: 1500,
    type: TransactionType.INCOME,
    method: PaymentMethod.TELEBIRR,
    note: 'Sales payment',
    vendor: 'Marketplace',
    reference: 'TB12345',
    date: new Date().toISOString(),
    isAutoGenerated: true
  },
  {
    id: 't2',
    amount: 1000,
    type: TransactionType.EXPENSE,
    method: PaymentMethod.CASH,
    category: ExpenseCategory.ROSCA_CONTRIBUTION,
    note: 'Weekly Equb contribution',
    date: new Date().toISOString(),
    isAutoGenerated: false
  }
];

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'a1',
    name: 'Commercial Store - Merkato',
    value: 2500000,
    category: AssetCategory.REAL_ESTATE,
    acquisitionDate: '2020-05-15',
    note: 'Prime location, leased to local vendors.'
  },
  {
    id: 'a2',
    name: 'Delivery Motorbike',
    value: 120000,
    category: AssetCategory.VEHICLE,
    acquisitionDate: '2023-01-10',
    note: 'Used for daily logistics.'
  }
];