export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN', // Managing Partner
  ADMIN = 'ADMIN',             // Operating Partner
  MEMBER = 'MEMBER'            // Audit Partner
}

export interface User {
  id: string;
  name: string;
  role: UserRole;
  pin: string;
  email: string;
  profilePic?: string;
  equityPercentage?: number;
  totalDividendsPaid?: number;
  joinedDate?: string;
}

export interface ChatMessage {
  id: string;
  senderId: string;
  senderName: string;
  text: string;
  timestamp: string;
  channel: 'GENERAL' | 'FINANCE' | 'STRATEGY';
}

export interface ActivityLog {
  id: string;
  userId: string;
  userName: string;
  action: string;
  timestamp: string;
  details?: string;
}

export interface ApprovalRequest {
  id: string;
  requesterId: string;
  requesterName: string;
  actionType: 'DELETE_TRANSACTION' | 'DELETE_ASSET' | 'DELETE_LOAN' | 'DELETE_EQUB';
  targetId: string;
  targetName: string;
  timestamp: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
}

export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  TRANSFER = 'TRANSFER',
  INVESTMENT = 'INVESTMENT',
  LOAN_PAYMENT = 'LOAN_PAYMENT'
}

export enum PaymentMethod {
  CASH = 'CASH',
  TELEBIRR = 'TELEBIRR',
  CBE = 'CBE',
  EBIRR = 'EBIRR'
}

export enum ExpenseCategory {
  BUSINESS = 'BUSINESS',
  PERSONAL = 'PERSONAL',
  ROSCA_CONTRIBUTION = 'ROSCA_CONTRIBUTION',
  TRANSPORT = 'TRANSPORT',
  FOOD = 'FOOD',
  UTILITIES = 'UTILITIES',
  OTHER = 'OTHER'
}

export enum AssetCategory {
  REAL_ESTATE = 'REAL_ESTATE',
  VEHICLE = 'VEHICLE',
  EQUIPMENT = 'EQUIPMENT',
  INVENTORY = 'INVENTORY',
  OTHER = 'OTHER'
}

export interface Asset {
  id: string;
  name: string;
  value: number;
  category: AssetCategory;
  acquisitionDate: string;
  note?: string;
}

export type Recurrence = 'DAILY' | 'WEEKLY' | 'EVERY_10_DAYS' | 'EVERY_15_DAYS' | 'MONTHLY' | 'BI_MONTHLY' | 'QUARTERLY';

export enum GoalType {
  SAVINGS = 'SAVINGS',
  LOAN_PAYOFF = 'LOAN_PAYOFF',
  ASSET_PURCHASE = 'ASSET_PURCHASE'
}

export enum GoalStatus {
  ON_TRACK = 'ON_TRACK',
  BEHIND = 'BEHIND',
  COMPLETED = 'COMPLETED'
}

export interface Goal {
  id: string;
  title: string;
  type: GoalType;
  targetAmount: number;
  currentAmount: number;
  startDate: string;
  deadline: string;
  fundingSource: PaymentMethod;
  contributionFrequency: 'DAILY' | 'WEEKLY' | 'MONTHLY';
  contributionAmount: number;
  status: GoalStatus;
}

export interface PlannedPayment {
  id: string;
  title: string;
  amount: number;
  dueDate: string;
  category: ExpenseCategory;
}

export interface Investment {
  id: string;
  investorName: string;
  amount: number;
  date: string;
  terms: string;
  returnType: 'NO_INTEREST';
}

export interface Loan {
  id: string;
  loanName: string;
  lenderName: string;
  totalAmount: number;
  requiredInitialSavings: number;
  netDisbursed: number;
  interestRate: number;
  durationMonths: number;
  monthlyRepayment: number;
  monthlyCompulsorySaving: number;
  totalInterest: number;
  totalPayableAmount: number;
  remainingAmount: number;
  startDate: string;
  endDate: string;
  nextPaymentDate: string;
  paymentMethod: PaymentMethod;
  paymentsMadeCount: number;
  paymentsRemainingCount: number;
  recurrence: Recurrence;
}

export interface EqubGroup {
  id: string;
  name: string;
  membersCount: number;
  currentRound: number;
  contributionAmount: number;
  frequency: Recurrence;
  startDate: string;
  myTurnIndex: number;
  joinedAtRound?: number;
  status: 'ACTIVE' | 'COMPLETED';
}

export interface Transaction {
  id: string;
  amount: number;
  type: TransactionType;
  method: PaymentMethod;
  toMethod?: PaymentMethod;
  category?: ExpenseCategory;
  note: string;
  vendor?: string;
  reference?: string;
  date: string;
  isAutoGenerated: boolean;
}

export interface WalletBalances {
  [PaymentMethod.CASH]: number;
  [PaymentMethod.TELEBIRR]: number;
  [PaymentMethod.CBE]: number;
  [PaymentMethod.EBIRR]: number;
}

export interface SentReport {
  id: string;
  generatedAt: string;
  month: string;
  year: number;
  senderId: string;
  recipientIds: string[];
  type: 'MONTHLY' | 'OCCASIONAL';
  occasionName?: string;
  status: 'PENDING' | 'SENT';
  approvedById?: string;
  approvedAt?: string;
  summary: {
    totalIncome: number;
    totalExpense: number;
    netBalance: number;
  };
}