import React, { useState } from 'react';
import { Smartphone, Send, Sparkles, AlertCircle } from 'lucide-react';
import { parseSmsToTransaction } from '../services/geminiService';
import { Transaction } from '../types';

interface SmsSimulatorProps {
  onParsed: (transaction: any) => void;
}

const SmsSimulator: React.FC<SmsSimulatorProps> = ({ onParsed }) => {
  const [smsText, setSmsText] = useState('');
  const [isParsing, setIsParsing] = useState(false);
  const [error, setError] = useState('');

  const templates = [
    "CBE: Received 5000.00 ETB from ABEBE BIKILA. Ref: CBE12345.",
    "Telebirr: You have received 1,200 ETB from Sara T. New balance is 5,400 ETB.",
    "eBirr: Sent 300 ETB to 0912345678. Fee 5 ETB.",
  ];

  const handleParse = async () => {
    if (!smsText.trim()) return;
    setIsParsing(true);
    setError('');
    
    const result = await parseSmsToTransaction(smsText);
    if (result) {
      onParsed({
        ...result,
        id: Math.random().toString(36).substr(2, 9),
        date: new Date().toISOString(),
        isAutoGenerated: true,
        note: `AI Parsed: ${result.vendor || 'Bank Transaction'}`
      });
      setSmsText('');
    } else {
      setError('Could not parse SMS. Please check the format.');
    }
    setIsParsing(false);
  };

  return (
    <div className="bg-slate-900 dark:bg-slate-950 text-white rounded-[2.5rem] p-8 shadow-2xl border border-white/10 text-left text-left">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-3 bg-indigo-600 rounded-2xl shadow-lg shadow-indigo-500/20">
          <Smartphone size={24} />
        </div>
        <div>
          <h3 className="text-xl font-black uppercase tracking-tight">SMS Auto-Reader</h3>
          <p className="text-slate-400 dark:text-slate-500 text-[10px] font-bold uppercase tracking-widest">Simulate incoming digital settlements</p>
        </div>
      </div>

      <div className="space-y-6">
        <div>
          <label className="block text-[10px] font-black text-slate-500 uppercase tracking-[0.2em] mb-3 ml-1">Message Stream</label>
          <textarea 
            className="w-full bg-slate-800 dark:bg-slate-900 border border-slate-700 dark:border-white/10 rounded-3xl p-6 text-sm font-medium focus:ring-4 focus:ring-indigo-500/20 outline-none transition-all h-32 resize-none text-slate-100 placeholder:text-slate-600"
            placeholder="e.g. CBE: Received 200 ETB..."
            value={smsText}
            onChange={(e) => setSmsText(e.target.value)}
          />
        </div>

        <div className="flex flex-wrap gap-2">
          {templates.map((t, idx) => (
            <button 
              key={idx}
              onClick={() => setSmsText(t)}
              className="px-4 py-2 bg-slate-800 dark:bg-slate-900 hover:bg-slate-700 dark:hover:bg-slate-800 rounded-xl text-[10px] font-black text-indigo-400 border border-slate-700 dark:border-white/5 transition-all active:scale-95 uppercase tracking-widest"
            >
              Feed Template {idx + 1}
            </button>
          ))}
        </div>

        {error && (
          <div className="flex items-center gap-3 p-4 bg-rose-500/10 text-rose-400 rounded-2xl text-xs font-bold border border-rose-500/20">
            <AlertCircle size={18} />
            {error}
          </div>
        )}

        <button 
          onClick={handleParse}
          disabled={isParsing || !smsText}
          className="w-full bg-indigo-600 text-white py-5 rounded-[2rem] font-black text-sm flex items-center justify-center gap-3 hover:bg-indigo-500 disabled:opacity-50 disabled:grayscale transition-all shadow-xl shadow-indigo-900/20 active:scale-95 uppercase tracking-widest"
        >
          {isParsing ? (
             <div className="w-6 h-6 border-4 border-white/30 border-t-white rounded-full animate-spin" />
          ) : (
            <>
              <Sparkles size={20} />
              Analyze Signal
            </>
          )}
        </button>
      </div>
    </div>
  );
};

export default SmsSimulator;